### PR TITLE
Bring up-to-date pre EE8 metro

### PR DESCRIPTION
**Pull request by hazendaz**
The current plugin fails with java 9.  This at least builds with java 9 but isn't to webservices-tools 2.4.0 yet and has another issue with wsimport.  In the meantime, wanted to raise things up to more recent times.

### CODE REVIEW

**Comment by hazendaz** [comment]
@trajano Has the changes originating from your repo made it to the main repo now owned by Eclipse?  At the moment, I got past all jdk9 and 10 issues.  However, jdk11, not so clear.  While Eclipse released versions to support it, they are missing artifacts in central, the same changes are pull requested against codehaus mojo, and no effective solution yet.  So more than anything, trying to figure out the status of this library.  Given that all 3 projects are now in github, it would make sense that only one moves forwards.  Currently I use this one as it worked best.  Codehaus has added a lot of changes, oracle added essentially none for a long time plus what was donated is deeply nested in other project...overly confusing...

I should note after many hours this weekend, I have the core Eclipse version working jdk8 through 10 without issue.  The module usage trips it up past that but it's been so many years I forget what the original purpose of this breakout was and presume that is now addressed.

**Comment by trajano** [comment]
Odd why is it failing on `rake`?

**Comment by trajano** [comment]
Also I don't know if it was merged, but I don't think we have the issue anymore otherwise someone from my old projects would have complained by now.

**Comment by hazendaz** [comment]
@trajano The latest EE4J release 2.3.2 seems to resolve everything.  I'm closing this as I have moved back to that.  Thanks for a good long run here :)

**Pull request closed without merging**
